package color

import "github.com/charmbracelet/lipgloss"

var (
    Black         = lipgloss.Color("0")
    Maroon        = lipgloss.Color("1")
    Green         = lipgloss.Color("2")
    Olive         = lipgloss.Color("3")
    Navy          = lipgloss.Color("4")
    Purple        = lipgloss.Color("5")
    Teal          = lipgloss.Color("6")
    Silver        = lipgloss.Color("7")
    Gray          = lipgloss.Color("8")
    Red           = lipgloss.Color("9")
    Lime          = lipgloss.Color("10")
    Yellow        = lipgloss.Color("11")
    Blue          = lipgloss.Color("12")
    Fuchsia       = lipgloss.Color("13")
    Aqua          = lipgloss.Color("14")
    White         = lipgloss.Color("15")
    LightGray     = lipgloss.Color("240")
    DarkGray      = lipgloss.Color("236")
    LightRed      = lipgloss.Color("196")
    LightGreen    = lipgloss.Color("118")
    LightYellow   = lipgloss.Color("226")
    LightBlue     = lipgloss.Color("81")
    LightMagenta  = lipgloss.Color("201")
    LightCyan     = lipgloss.Color("123")
    BrightWhite   = lipgloss.Color("15")
    BrightBlack   = lipgloss.Color("8")
    BrightRed     = lipgloss.Color("9")
    BrightGreen   = lipgloss.Color("10")
    BrightYellow  = lipgloss.Color("11")
    BrightBlue    = lipgloss.Color("12")
    BrightMagenta = lipgloss.Color("13")
    BrightCyan    = lipgloss.Color("14")
)

